### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by yangop8** [queryproc/optimizing-subgraph-queries-combining-binary-and-worst-case-optimal-joins#1]
After I build the graphflow and change snap to edges.csv, I run the following command:
`python serialize_dataset.py /absolute/dataset/edges.csv /absolute/data`
but I got the following error:
**No such file or directory: '/GRAPHFLOW_HOME/build/install/graphflow/bin/dataset-serializer': '/GRAPHFLOW_HOME/build/install/graphflow/bin/dataset-serialize**
It seems that the build step didn't generate the whole graphflow.
I also git clone the [graphflow repo](https://github.com/colinsongf/graphflow) and it can generate **'/GRAPHFLOW_HOME/build/install/graphflow/bin/**, but not the scripts to load data.
I guess that might be something wrong? 

Looking forward to your reply!

**Comment by yangop8** [comment]
It has  **'/GRAPHFLOW_HOME/build/scripts/'** but not  **'/GRAPHFLOW_HOME/build/install/graphflow/bin/'**.

**Comment by queryproc** [comment]
once you built the graph, make sure to run
```
. ./env.sh
```
To create the GRAPHFLOW_HOME env variable. Once there simply go to the scripts directory and execute the scripts as necessary.

For specific guidance or answers regarding your setup, feel free to email me directly.
