### ISSUE TITLE
About the size of the adjacency list

### ISSUE THREAD

**Issue by fyulingi** [queryproc/optimizing-subgraph-queries-combining-binary-and-worst-case-optimal-joins#3]
![image](https://user-images.githubusercontent.com/52391898/111558745-55f20500-87ca-11eb-9a35-139939166b90.png)

In the class SortedAdjList, there is a function named "size". However, I think is should be "-" in the return statement. (Because in the offset, offset[i] is the number of all type(label) not bigger than i)

**Comment by fyulingi** [comment]
Looking forward to your reply, thanks!

**Comment by queryproc** [comment]
This is indeed a bug. I will push a fix. Note however that size() is not called directly. 
The Extend operator access the offsets directly as such:
```Java
for (var idx = outNeighbours.startIdx; idx < outNeighbours.endIdx; idx++) {
    ...
}
```
and inside SortedAdjList in the intersect(short labelOrType, Neighbours someNeighbours, Neighbours neighbours) method.
```Java
return labelOrTypeOffsets[labelOrType + 1] - labelOrTypeOffsets[labelOrType];
```

**Comment by fyulingi** [comment]
Thanks!

I have another question which is about processNewtuple method in the EI class (also in extend, intersect, intersectcatalog subclass).
I am wondering for example, if we find two nodes in scan "(a)->(b)", then we need to extend to (c) by (a)[Fwd](0) (suppose the dataset only have one type 0 and one label 0 for simplicity). In the processNewtuple method, it seems have not check (c) is just (b) (in setNeighbourIds method).

**Comment by fyulingi** [comment]
Maybe my example does not catch the point, here is another example:

In query "(a)->(b), (a)->(c), (b)->(c), (a)->(d), (b)->(d)", (c) and (d) might be the same node.
